add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_status]($style)$character"

# Username module with Hakker theme colors
[username]
show_always = true
style_user = "bg:#000000 fg:#00ff99"
style_root = "bg:#000000 fg:#ccffee"
format = '[$user ]($style)'
disabled = false

# Character module for the prompt symbol
[character]
success_symbol = '[‚ûú](fg:#00ff99)'
error_symbol = '[‚úó](fg:#ccffee)'
vicmd_symbol = '[‚ùÆ](fg:#00cc77)'

[directory]
# truncation_length = 2
# truncation_symbol = "‚Ä¶/"
repo_root_style = "bold fg:#00cc77"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
style = "fg:#00cc77"
format = "[ $path ]($style)"

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "fg:#00ff99"
ahead      = "‚á°${count} "
diverged   = "‚áï‚á°${ahead_count}‚á£${behind_count} "
behind     = "‚á£${count} "
conflicted = "ÓÆ´ "
up_to_date = "ÔÄå "
untracked  = "? "
modified   = "Ó©± "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

# Path substitutions for cleaner display
[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = "ÔÄô "
"Music" = "ÔÄÅ "
"Pictures" = "ÔÄæ "
"Desktop" = "Û∞Äæ "
"Videos" = "Û∞ïß "
"Public" = "Û∞êï "
"Templates" = "Û∞èó "

# Docker context with Hakker theme
[docker_context]
symbol = "Û∞°® "
style = "bg:#ccffee fg:#000000"
format = '[ $symbol $context ]($style)'

# Git branch with Hakker theme
# [git_branch]
# symbol = "Û∞ò¨"
# style = "bg:#00ff99 fg:#000000"
# format = '[ $symbol $branch ]($style)'
#
# # Git status with Hakker theme
# [git_status]
# style = "bg:#00ff99 fg:#000000"
# format = '[$all_status$ahead_behind ]($style)'

# Programming language modules with Hakker theme
[golang]
symbol = "Û∞üì "
style = "bg:#383838 fg:#00ff99"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#383838 fg:#00ff99"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "Û∞∏≠ "
style = "bg:#383838 fg:#00ff99"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "Û∞åûÛ∞õ¶"
style = "bg:#383838 fg:#00ff99"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "Û±òó"
style = "bg:#383838 fg:#00ff99"
format = '[ $symbol ($version) ]($style)'

[python]
version_format = "${raw}"
symbol = " üêç "
style = "bg:#383838 fg:#00ff99"
format = '[${symbol}${version} Û∞å†($virtualenv)Û∞å† ]($style)'
